### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by moplin** [yii2tech/sitemap#2]
From where is this taking the domain?
I am having a problem when building the site map, because its building it as domain.dev and not the final domain.
So where do I change it or how can I specify the domain name.

Thanks

**Comment by klimov-paul** [comment]
You should configure your 'urlManager' component for the console application, mocking up host information.
You can check [yii2tech/project-template](https://github.com/yii2tech/project-template) for working example.

https://github.com/yii2tech/project-template/blob/master/config/local.php.sample#L21-L25
https://github.com/yii2tech/project-template/blob/master/config/frontend-url-manager.php#L8-L9
