### ISSUE TITLE
Don't close root tag in getContent method

### ISSUE THREAD

**Issue by shurik2k5** [yii2tech/sitemap#7]
### What steps will reproduce the problem?
Try to generate sitemap in memory with cache with Yii cache component.
### What is the expected result?
return sitemap content with close root tag
### What do you get instead?
root tag doesn't close

### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.1.0
| Yii Framework Version | 2.0.28
| PHP version           | 7.2.23
| Operating system      | Ubuntu 18.04 x64

**Comment by klimov-paul** [comment]
Resolved by commit ce6ee63c02108f39334314a49a58fbb07b4d96fd
Thank you for the reporting.
