### ISSUE TITLE
Adding extracontent with ":" broke the output

### ISSUE THREAD

**Issue by infoitservit** [yii2tech/sitemap#9]
### What steps will reproduce the problem?
Try to add to any line the extracontent "<xhtml:link
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>"

### What is the expected result?
The extracontent is appended to the current url tag

### What do you get instead?
An output completely broken
### Additional info
The problem is related to the ":" in "xhtml:link". Removing ":" it works.

| Q                     | A
| --------------------- | ---
| This Package Version  | last packages
| Yii Framework Version | 2.0.40
| PHP version           |  7.4
| Operating system    | Ubuntu 20.04

**Comment by klimov-paul** [comment]
Unable to reproduce.
`yii2tech\sitemap\File::writeUrl()` does not alters the value of `$extraContent` argument anyhow.
Please search for the error at other place of your code.
